name: Sector 7 Records
favicon: null
layout_spectrum: 0.50608
typography_spectrum: 0.78432
title: Sector 7 Records
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#424242'
    - '#cfcfcf'
    - '#838383'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
